<a href="https://colab.research.google.com/github/strangecod/360/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
l=[1,2,3,4]
np.array(l)


array([1, 2, 3, 4])

In [ ]:
np.array(l)

array([1, 2, 3, 4])

In [ ]:
arr1=np.asarray(l)

In [ ]:
arr=np.array([[1,2,3,],[2,3,4]])

In [ ]:
arr.ndim

2

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
print(type(arr1))

<class 'numpy.ndarray'>


In [ ]:
np.asanarray([mat])

NameError: name 'mat' is not defined

In [ ]:
a=arr

In [ ]:
print(a)

[[1 2 3]
 [2 3 4]]


In [ ]:
a[0][0]=100

In [ ]:
print(a)

[[100   2   3]
 [  2   3   4]]


In [ ]:
print(arr)

[[100   2   3]
 [  2   3   4]]


In [ ]:
b=np.copy(arr)

In [ ]:
b[0][1]=200

In [ ]:
print(b)

[[100 200   3]
 [  2   3   4]]


In [ ]:
print(arr)

[[100   2   3]
 [  2   3   4]]


In [ ]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
iterable=(i*3 for i in range(5))

In [ ]:
np.fromiter(iterable,float)

array([], dtype=float64)

In [ ]:
np.fromstring('23,45,34',sep = ',')  //converting the string into array

array([23., 45., 34.])

In [ ]:
arr.size

6

In [ ]:
arr.shape

(2, 3)

In [ ]:
np.arange(.4, 10.4, 0.2)  //for forming the array

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [ ]:
np.linspace(1,5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
np.logspace(1,5, 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
arr4=np.ones((3,4))

In [ ]:
arr4+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
np.empty((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [17]:
arr5=np.eye(5) //for forming the diagonal shape aray

In [ ]:
import pandas as pd


In [ ]:
pd.DataFrame(arr5)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1[0].plot(kind='hist', bins=20, title=0)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2[1].plot(kind='hist', bins=20, title=1)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3[2].plot(kind='hist', bins=20, title=2)
plt.gca().spines[['top', 'right',]].set_visible(False)

KeyError: '0'

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='index', y='0', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x=0, y=1, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x=1, y=2, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x=2, y=3, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series[0]
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel(0)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series[1]
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel(1)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series[2]
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel(2)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series[3]
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel(3)

from matplotlib import pyplot as plt
_df_12['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_13[0].plot(kind='line', figsize=(8, 4), title=0)
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_14[1].plot(kind='line', figsize=(8, 4), title=1)
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_15[2].plot(kind='line', figsize=(8, 4), title=2)
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
np.random.rand(2,3)

array([[0.49886632, 0.86099543, 0.38264608],
       [0.75168633, 0.09155072, 0.84478259]])

In [ ]:
arr1=np.random.randint(1,5, (3,4)) //for importing the random elements in array

In [ ]:
arr1

array([[3, 1, 2, 4],
       [1, 3, 3, 2],
       [1, 2, 4, 1]])

In [ ]:
arr1.shape

(3, 4)

In [ ]:
arr1.reshape(2,2,3)

array([[[3, 1, 2],
        [4, 1, 3]],

       [[3, 2, 1],
        [2, 4, 1]]])

In [ ]:
arr3=np.random.randint(1,8, (3,4))

In [ ]:
arr3

array([[1, 6, 4, 5],
       [5, 6, 4, 3],
       [2, 6, 7, 7]])

In [ ]:
arr3>4

array([[False,  True, False,  True],
       [ True,  True, False, False],
       [False,  True,  True,  True]])

In [ ]:
arr3[arr3>4]

array([6, 5, 5, 6, 6, 7, 7])

In [ ]:
arr3

array([[1, 6, 4, 5],
       [5, 6, 4, 3],
       [2, 6, 7, 7]])

In [ ]:
arr3[0]

array([1, 6, 4, 5])

In [ ]:
arr3[1,[1,2]]

array([6, 4])

In [ ]:
arr3[2:3,[1,2]]

array([[6, 7]])

In [ ]:
arr1=np.random.randint(1,4,(3,3))
arr2=np.random.randint(5,9,(3,3))

In [ ]:
arr1
arr2

array([[6, 6, 7],
       [6, 7, 8],
       [7, 7, 8]])

In [ ]:
arr2

array([[6, 6, 7],
       [6, 7, 8],
       [7, 7, 8]])

In [ ]:
arr1

array([[3, 2, 3],
       [1, 2, 2],
       [1, 1, 3]])

In [ ]:
arr1+arr2

array([[ 9,  8, 10],
       [ 7,  9, 10],
       [ 8,  8, 11]])

In [ ]:
# Array Manupilation

In [2]:
import numpy as np //for impoting the power of araay and matrix formation

In [7]:
arr=np.random.randint(1,10, (4,4))

In [14]:
arr1=arr.reshape(2,8) //reshapes the array

arr.T

In [15]:
arr1.T

array([[5, 5],
       [3, 6],
       [7, 9],
       [7, 1],
       [8, 9],
       [6, 1],
       [3, 8],
       [9, 5]])

In [16]:
arr.flatten() //convert the 2d array into a single array

array([5, 3, 7, 7, 8, 6, 3, 9, 5, 6, 9, 1, 9, 1, 8, 5])

In [19]:
arr

array([[5, 3, 7, 7],
       [8, 6, 3, 9],
       [5, 6, 9, 1],
       [9, 1, 8, 5]])

In [21]:
np.expand_dims(arr,axis=1) //forming the dimension the array forming differetent rows

array([[[5, 3, 7, 7]],

       [[8, 6, 3, 9]],

       [[5, 6, 9, 1]],

       [[9, 1, 8, 5]]])

In [22]:
data=np.array([[1],[2],[3]])

In [23]:
np.squeeze(data)  //squeezes the n dimension array into single dimenion array

array([1, 2, 3])

In [24]:
np.repeat(data,2)  //repeates the eleemtns

array([1, 1, 2, 2, 3, 3])

In [26]:
np.roll(data,2)  //repeats the data by 2 times in arary

array([[2],
       [3],
       [1]])

In [27]:
np.diag(np.array([1,2,3]))  //converts into diagonal

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [28]:
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))

In [29]:
arr1+arr2

array([[13, 10,  7],
       [ 8,  4,  3],
       [ 7, 14,  4]])

In [30]:
arr1*arr2

array([[42,  9, 12],
       [15,  3,  2],
       [ 6, 45,  3]])

In [31]:
arr1/arr2

array([[0.85714286, 0.11111111, 1.33333333],
       [0.6       , 0.33333333, 2.        ],
       [0.16666667, 0.55555556, 3.        ]])

In [32]:
arr1-arr2

array([[-1, -8,  1],
       [-2, -2,  1],
       [-5, -4,  2]])

In [33]:
arr1**arr2

array([[ 279936,       1,      64],
       [    243,       1,       2],
       [      1, 1953125,       3]])

In [34]:
~arr1

array([[-7, -2, -5],
       [-4, -2, -3],
       [-2, -6, -4]])

In [35]:
arr1>arr2

array([[False, False,  True],
       [False, False,  True],
       [False, False,  True]])

In [ ]:
# numpy in string

In [36]:
arr=np.array(["hello","world"])

In [37]:
arr

array(['hello', 'world'], dtype='<U5')

In [39]:
np.char.upper(arr)

array(['HELLO', 'WORLD'], dtype='<U5')

In [41]:
np.char.capitalize(arr)

array(['Hello', 'World'], dtype='<U5')

In [43]:
np.char.title(arr)

array(['Hello', 'World'], dtype='<U5')

In [45]:
np.sin(arr1)

array([[-0.2794155 ,  0.84147098, -0.7568025 ],
       [ 0.14112001,  0.84147098,  0.90929743],
       [ 0.84147098, -0.95892427,  0.14112001]])

In [46]:
np.cos(arr1)

array([[ 0.96017029,  0.54030231, -0.65364362],
       [-0.9899925 ,  0.54030231, -0.41614684],
       [ 0.54030231,  0.28366219, -0.9899925 ]])

In [47]:
np.tan(arr1)

array([[-0.29100619,  1.55740772,  1.15782128],
       [-0.14254654,  1.55740772, -2.18503986],
       [ 1.55740772, -3.38051501, -0.14254654]])

In [48]:
np.log(arr1)

array([[1.79175947, 0.        , 1.38629436],
       [1.09861229, 0.        , 0.69314718],
       [0.        , 1.60943791, 1.09861229]])

In [52]:
np.power(arr1,2)

array([[36,  1, 16],
       [ 9,  1,  4],
       [ 1, 25,  9]])

In [53]:
np.median(arr1)

3.0

In [54]:
np.max(arr1)

6

In [55]:
np.min(arr1)

1

In [56]:
np.multiply(arr1,arr2)

array([[42,  9, 12],
       [15,  3,  2],
       [ 6, 45,  3]])

In [57]:
np.sqrt(arr1)

array([[2.44948974, 1.        , 2.        ],
       [1.73205081, 1.        , 1.41421356],
       [1.        , 2.23606798, 1.73205081]])

In [ ]:
# statistical operation

In [58]:
np.mean(arr1)

2.888888888888889

In [59]:
np.median(arr1)

3.0

In [ ]:
# sort, search,counting operations

In [60]:
import numpy as np

In [64]:
arr=np.array([5,1,9,3,6])

In [65]:
np.sort(arr)

array([1, 3, 5, 6, 9])

In [70]:
np.searchsorted(arr,4)

2

In [73]:
arr1=np.array([1,2,3,0,0,7,0,5,0,3,0,4,4,4,4])

In [74]:
np.count_nonzero(arr1)

10

In [75]:
np.where(arr1>0)  //on which indices the numbers are greater than zero

(array([ 0,  1,  2,  5,  7,  9, 11, 12, 13, 14]),)

In [76]:
np.extract(arr1>2,arr1)

array([3, 7, 5, 3, 4, 4, 4, 4])

In [ ]:
# byte swapping

In [78]:
arr1.byteswap()

array([ 72057594037927936, 144115188075855872, 216172782113783808,
                        0,                  0, 504403158265495552,
                        0, 360287970189639680,                  0,
       216172782113783808,                  0, 288230376151711744,
       288230376151711744, 288230376151711744, 288230376151711744])

In [ ]:
# cpies and views

In [79]:
a=np.copy(arr1)

In [81]:
b=arr1.view()

In [82]:
b[0]=234

In [83]:
b

array([234,   2,   3,   0,   0,   7,   0,   5,   0,   3,   0,   4,   4,
         4,   4])

In [ ]:
# matrix library

In [84]:
import numpy.matlib as nm

In [ ]:
nm.zeros(5)